Bloque_optimo.pdf:Bloque_optimo_T.txt Bloque_optimo_M.txt
	gnuplot ../Codigo/BO.gp

mult-TIME_vs_NB-O0.pdf:multiplicacion_blocking.txt multiplicacion_eigen.txt multiplicacion_armadillo.txt
	gnuplot ../Codigo/MT0.gp
	gnuplot ../Codigo/MM0.gp

mult-TIME_vs_NB-O3.pdf:multiplicacion_blocking_O3.txt multiplicacion_eigen_O3.txt multiplicacion_armadillo_O3.txt
	gnuplot ../Codigo/MT3.gp
	gnuplot ../Codigo/MM3.gp

trans-TIME_vs_NB-O0.pdf:transpuesta_blocking.txt transpuesta_eigen.txt transpuesta_armadillo.txt
	gnuplot ../Codigo/TT0.gp
	gnuplot ../Codigo/TM0.gp

trans-TIME_vs_NB-O3.pdf:transpuesta_blocking_O3.txt transpuesta_eigen_O3.txt transpuesta_armadillo_O3.txt
	gnuplot ../Codigo/TT3.gp
	gnuplot ../Codigo/TM3.gp
